# Generated by Django 5.0.2 on 2024-03-01 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('system_for_study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_link', models.URLField()),
                ('product',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_for_study.product')),
            ],
        ),
    ]
