# Generated by Django 5.0.2 on 2024-03-01 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('system_for_study', '0002_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_users', models.IntegerField()),
                ('max_users', models.IntegerField()),
                ('product',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_for_study.product')),
                ('students', models.ManyToManyField(related_name='group_students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
