# Generated by Django 5.0.2 on 2024-03-01 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('system_for_study', '0003_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
